include "../../..//src/Collections/Maps/Imaps.dfy"
module srcCollectionsMapsImapsdfyUnitTests {
import Imaps
import Wrappers
// Merging boogie files...
// Converting function calls to method calls...
// Adding Impl$$ methods to support inlining...
// Removing assertions...
// Annotating blocks...
// Generating modifications...
// Test Imaps.Get(block#286917) covers block 286914
// Test Imaps.Get(block#286917) covers block 286915
// Test Imaps.Get(block#286917) covers block 286917
// Extracting the test for Imaps.Get(block#286917) from the counterexample...
// Failed to determine a variable type (element T@U!val!11)
// Test Imaps.Get(block#286916) covers block 286914
// Test Imaps.Get(block#286916) covers block 286916
// Extracting the test for Imaps.Get(block#286916) from the counterexample...
// Failed to determine a variable type (element T@U!val!42)

}
