include "../../..//src/Collections/Maps/Imaps.dfy"
module srcCollectionsMapsImapsdfyUnitTests {
import Imaps
import Wrappers
// Merging boogie files...
// Converting function calls to method calls...
// Adding Impl$$ methods to support inlining...
// Removing assertions...
// Annotating blocks...
// Generating modifications...
// Test Imaps.Get(block#261760) covers block 261757
// Test Imaps.Get(block#261760) covers block 261758
// Test Imaps.Get(block#261760) covers block 261760
// Extracting the test for Imaps.Get(block#261760) from the counterexample...
method {:test} test0() {
var d0 : imap<int, int> := imap[];
var r0 := Imaps.Get<int,int>(d0, 0);
}
// Test Imaps.Get(block#261759) covers block 261757
// Test Imaps.Get(block#261759) covers block 261759
// Extracting the test for Imaps.Get(block#261759) from the counterexample...
// Test for Imaps.Get(block#261759) matches a test previously generated for Imaps.Get(block#261760).

}
