include "../../..//src/NonlinearArithmetic/Internals/DivInternalsNonlinear.dfy"
module srcNonlinearArithmeticInternalsDivInternalsNonlineardfyUnitTests {
import DivInternalsNonlinear
// Merging boogie files...
// Converting function calls to method calls...
// Adding Impl$$ methods to support inlining...
// Removing assertions...
// Annotating blocks...
// Generating modifications...

}
