include "../../..//src/NonlinearArithmetic/Internals/GeneralInternals.dfy"
module srcNonlinearArithmeticInternalsGeneralInternalsdfyUnitTests {
import GeneralInternals
// Merging boogie files...
// Converting function calls to method calls...
// Adding Impl$$ methods to support inlining...
// Removing assertions...
// Annotating blocks...
// Generating modifications...

}
