include "../../..//src/NonlinearArithmetic/Internals/ModInternalsNonlinear.dfy"
module srcNonlinearArithmeticInternalsModInternalsNonlineardfyUnitTests {
import ModInternalsNonlinear
// Merging boogie files...
// Converting function calls to method calls...
// Adding Impl$$ methods to support inlining...
// Removing assertions...
// Annotating blocks...
// Generating modifications...

}
