include "../../..//src/NonlinearArithmetic/Internals/MulInternalsNonlinear.dfy"
module srcNonlinearArithmeticInternalsMulInternalsNonlineardfyUnitTests {
import MulInternalsNonlinear
// Merging boogie files...
// Converting function calls to method calls...
// Adding Impl$$ methods to support inlining...
// Removing assertions...
// Annotating blocks...
// Generating modifications...

}
